Initial commit
The-Academic-Observatory/academic-observatory-workflows pull request #3
Opened 2021-08-31 00:22 UTC by jdddog

2021-08-31 05:45 UTC, aroelo requested changes
Hey Jamie,
Looks good to me, but the new transform_batch function is not covered by the unit tests.
I wonder if those lines are actually covered, but not picked up somehow because of the processpoolexecutor?

2021-08-31 22:21 UTC, jdddog commented
> Hey Jamie,
> Looks good to me, but the new transform_batch function is not covered by the unit tests.
> I wonder if those lines are actually covered, but not picked up somehow because of the processpoolexecutor?

Thanks Aniek, ah maybe, I'll take a look

2021-09-03 00:31 UTC, jdddog commented
> Hey Jamie,
> Looks good to me, but the new transform_batch function is not covered by the unit tests.
> I wonder if those lines are actually covered, but not picked up somehow because of the processpoolexecutor?

Yeah that seems to be the case, I've changed that last test a little bit so now that it is covered.

2021-09-03 01:05 UTC, aroelo approved these changes

2021-09-03 01:15 UTC, merged