Inf 40/create unpaywall data feed telescope
The-Academic-Observatory/academic-observatory-workflows pull request #39
Opened 2021-09-24 23:30 UTC by tuanchien

2021-09-29 23:08 UTC, jdddog requested changes
It looks good to me Tuan, just a few small comments.

2021-09-29 23:08 UTC, jdddog commented on academic_observatory_workflows/workflows/unpaywall_data_feed_telescope.py
> +    def download_snapshot_(self):
Private methods in Python should begin with an underscore, not end with an underscore, e.g. _download_snapshot.

2021-09-29 23:08 UTC, jdddog commented on academic_observatory_workflows/workflows/unpaywall_data_feed_telescope.py
> +    def download_data_feed_(self):
Private methods in Python should begin with an underscore, not end with an underscore, e.g. _download_snapshot.

2021-09-29 23:08 UTC, jdddog commented on academic_observatory_workflows/workflows/unpaywall_data_feed_telescope.py
> +    def schedule_days_apart_(
Private methods in Python should begin with an underscore, not end with an underscore, e.g. _download_snapshot.

2021-09-29 23:08 UTC, jdddog commented on academic_observatory_workflows/workflows/unpaywall_data_feed_telescope.py
> +    def validate_schedule_interval_(self, *, start_date: pendulum.DateTime, schedule_interval: str):
Private methods in Python should begin with an underscore, not end with an underscore, e.g. _download_snapshot.

2021-09-29 23:08 UTC, jdddog commented on academic_observatory_workflows/workflows/unpaywall_data_feed_telescope.py
> +    def get_release_info_(self, **kwargs) -> Tuple[pendulum.DateTime, bool]:
Private methods in Python should begin with an underscore, not end with an underscore, e.g. _download_snapshot.

2021-09-29 23:08 UTC, jdddog commented on docs/telescopes/unpaywall_data_feed.md
> +
It would be good to put an example the required Airflow Connection in the documentation, i.e. the key name and the connection URI.

2021-09-29 23:47 UTC, jdddog approved these changes
Thanks Tuan, looks good to me!

2021-09-29 23:55 UTC, merged

2021-09-30 01:53 UTC, aroelo commented
@tuanchien Did you test whether the BigQuery functionality works with catchup=True?
Witch catchup set to True, there could be multiple dag runs on the same day. 
The partitions that are created in the bq_load_partition task are ingestion time partitions, meaning that the partition date (and table id) is based on the ingestion date, which could possibly be the same for multiple Dag Runs.
I'm not sure if the data is then properly handled or if it is e.g. overwritten?

2021-09-30 02:42 UTC, tuanchien commented
@aroelo I did not test that bit. You're right, I think there is an issue.  However, according to https://cloud.google.com/bigquery/docs/managing-partitioned-table-data#write-to-partition we can target explicit partition dates even with ingestion based partitioning.

I haven't looked closely into the details of the stream telescope, and its bq functions, but perhaps, if we change
https://github.com/The-Academic-Observatory/observatory-platform/blob/64b62cba83110fea60e91506dff4a83ba9931ba9/observatory-platform/observatory/platform/utils/workflow_utils.py#L440

from:
```
partition_table_id = create_date_table_id(partition_table_id, pendulum.today(), partition_type)
```

to
```
partition_table_id = create_date_table_id(partition_table_id, release.start_date, partition_type)
```
that might do it (```end_date``` is another option).

2021-09-30 08:05 UTC, aroelo commented
> https://github.com/The-Academic-Observatory/observatory-platform/blob/64b62cba83110fea60e91506dff4a83ba9931ba9/observatory-platform/observatory/platform/utils/workflow_utils.py#L440

Yeah I think changing it to the release.end_date would be a good alternative, I've made that change in the PR that is already open and related to the StreamTelescope (https://github.com/The-Academic-Observatory/observatory-platform/pull/496/commits/fced3e713de3e41eac22190e5214c2af21c252f3)